### ISSUE TITLE
can't draw custom geofence with irregular(polygonal) shape 

### ISSUE THREAD

**Issue by kawadkarrocky** [vhoen/Android-Geofence-21#2]
Hey there, I was tried this tutorial it works very well, but I need to draw geofence with irregular shape like polygon since the Google maps API suggested to use Geofence.Builder() class to build the geofence with its regular circular shape but have no implentational methods to draw polygon of irregular shape. also I tried to built it by Polygon options but unable to find area of interior of polygon so please will anyone help me to find the interior area of that shape so to allow notification whenever user enters in that polygonal area and notifying when exiting that area, thank you.

**Comment by vhoen** [comment]
As far as I know, a geofence must be a circle since it's [created](https://developer.android.com/training/location/geofencing.html#CreateAdd) by passing it a latitude, a longitude and a radius. It's possible to represent it on a map using a [circle](https://developers.google.com/android/reference/com/google/android/gms/maps/model/Circle) to which you pass a latlng and a radius.

**Comment by kawadkarrocky** [comment]
Hello Sir, but what if I want to create my custom GeoFence of any polygon say rectangle of regular shape 
by taking all the area inside the rectangle, so is there any way possible to do that????????? by considering latlng of all interior part of rectangle. any help would be appreciated....

**Comment by vhoen** [comment]
I do understand your problem, but as far as I know, it can't be done (I would be glad to be proved wrong). 
The only way I can think of is to create a geofence that covers your polygonal area. Also, bear in mind that the accuracy range can be a little [off](https://developer.android.com/training/location/geofencing.html#BestPractices)
